#!/bin/bash

DIR=$(cd $(dirname $0); pwd -P)
source ${DIR}/config.sh
source ${DIR}/include.sh

function usage {
  echo "USAGE $(basename $0) validate | apply | show [-w]"
  exit 1
}

if [ $# -lt 1 ]; then
  usage
fi

action="$1"
watch=0
if [ "$2" == "-w" ]; then
  watch=1
fi

if [ "${action}" == "validate" ]; then
  ${SPL} validate cluster-bundle
elif [ "${action}" == "apply" ]; then
 ${SPL} apply cluster-bundle
elif [ "${action}" == "show" ]; then
  if [ $watch -eq 1 ]; then
    while true; do
      clear
      ${SPL} show cluster-bundle-status
      sleep 2
    done
  else
    ${SPL} show cluster-bundle-status
  fi
else
  usage
fi
