#!/bin/bash

source $(dirname $0)/config.sh

function usage {
	echo "USAGE: $(basename $0) app configfile [-d]"
	echo "  -d: doit: overwrites the existing default/<configfile>.conf file and deletes the local/<configfile>.conf file"
	exit 1
}

# Arguments
if [ $# -lt 2 ]; then
	usage
fi
APP="$1"
CFG="$2"
DOIT=0
if [ "$3" == "-d" ]; then
	DOIT=1	
fi

TMP=$(mktemp -d)
TS=$(date +%Y%m%d%H%M%S)

echo -n "Creating new consolidated default config ${CFG}.conf..."
first=1
{
while read line
do
	if [ "${line:0:1}" == "/" ]; then
		if [ $first -eq 0 ]; then
			printf "\n"
		fi
		out="$(echo "$line" | cut -d' ' -f 2- | sed -E 's,^[[:space:]]+,,')"
		if [ $first -eq 0 -a "${out:0:1}" == "[" ]; then
			printf "\n%s" "$out"
		else
			printf "%s" "$out" 
		fi
	else
		printf " \\\\\n"
		printf "%s" "$line"
	fi		
	first=0
done< <($BT "${CFG}" list --app="${APP}" --debug-print=sourcefile | sed -e 's,\\,\\\\,g')
} > "${TMP}/${CFG}.conf"
echo -e "\033[0;32mDONE\033[0m"

if [ $DOIT -eq 1 ]; then
	echo -n "Creating backup ${APP}/default/${CFG}.conf -> ${APP}/default/${CFG}.conf-${TS}..."
	if MSG=$(mv "${SPLAPPS}/${APP}/default/${CFG}.conf" "${SPLAPPS}/${APP}/default/${CFG}.conf-${TS}" 2>&1); then
		echo -e "\033[0;32mDONE\033[0m"
	else
		echo -e "\033[0;31m\nERROR: ${MSG}\033[0m"
	fi

	echo -n "Creating backup ${APP}/local/${CFG}.conf -> ${APP}/local/${CFG}.conf-${TS}..."
	if MSG=$(mv "${SPLAPPS}/${APP}/local/${CFG}.conf" "${SPLAPPS}/${APP}/local/${CFG}.conf-${TS}" 2>&1); then
		echo -e "\033[0;32mDONE\033[0m"
	else
		echo -e "\033[0;31m\nERROR: ${MSG}\033[0m"
	fi

	echo -n "Replacing the original default config ${CFG}.conf..."
	if MSG=$(cp "${TMP}/${CFG}.conf" "${SPLAPPS}/${APP}/default/${CFG}.conf" 2>&1); then
		echo -e "\033[0;32mDONE\033[0m"
	else
		echo -e "\033[0;31m\nERROR: ${MSG}\033[0m"
	fi
	rm -rf ${TMP}
else
	echo "File is at ${TMP}"
fi

