#!/bin/bash

DIR=$(cd $(dirname $0); pwd -P)
source ${DIR}/config.sh
source ${DIR}/include.sh

function usage {
  echo "USAGE $(basename $0) clients"
  exit 1
}

function out {
  printf "%-36s | %-20s | %-20s | %-40s | %s\n" "${CN}" "${HN}" "${DNS}" "${CLASSES}" "${APPS}"
  CN=''; HN=''; DNS=''; APPS=''; CLASSES=''
}

if [ $# -lt 1 ]; then
  usage
fi

action="$1"
CN='CLIENT'; HN='HOSTNAME'; DNS='DNS'; APPS='APPS'; CLASSES='CLASSES'

if [ "${action}" == "clients" ]; then
  while read line
  do
    if echo $line | grep "clientName:" 2>&1 >/dev/null; then
      CN=$(echo $line | cut -d':' -f2 | sed -E 's, ,,g')
    fi
    if echo $line | grep "hostname:" 2>&1 >/dev/null; then
      HN=$(echo $line | cut -d':' -f2 | sed -E 's, ,,g')
    fi
    if echo $line | grep "dns:" 2>&1 >/dev/null; then
      DNS=$(echo $line | cut -d':' -f2 | sed -E 's, ,,g')
    fi
    if echo $line | grep "applications:" 2>&1 >/dev/null; then
      APPS=$(echo $line | sed -E 's,.*applications: ,,g' | sed -E "s,'',,g" | sed -E "s,',\\\",g" | sed -E 's,None,\"None\",g' | jq -r 'keys | join(", ")')
    fi
    if echo $line | grep "serverClasses:" 2>&1 >/dev/null; then
      CLASSES=$(echo $line | sed -E 's,.*serverClasses: ,,g')
      if [ "$CLASSES" != "None" ]; then
        CLASSES=$(echo "${CLASSES}" | sed -E "s,',\\\",g" | sed -E 's,None,\"None\",g' | jq -r 'keys | join(", ")')
      fi
    fi
    if echo $line | grep "Deployment client:" 2>&1 >/dev/null; then
      out
    fi
  done < <(${SPL} list deploy-clients)
  out
elif [ "${action}" == "edit" ]; then
  vi ${SPLHOME}/etc/system/local/serverclass.conf
  ${SPL} btool check
elif [ "${action}" == "reload" ]; then
  if ${SPL} btool check; then
    ${SPL} reload deploy-server
  else
    echo "I do not reload because of errors in config!"
  fi
else
  usage
fi
