#!/bin/bash

DIR=$(cd $(dirname $0); pwd -P)
source ${DIR}/config.sh
source ${DIR}/include.sh

function usage {
  echo "USAGE $(basename $0) add|remove|update app host"
  exit 1
}

if [ $# -lt 3 ]; then
  usage
fi

action="$1"
app="$2"
target="$3"

if [ "${action}" == "add" -o "${action}" == "update" ]; then
	scp -r ${SPLHOME}/etc/deployment-apps/${app} ${target}:${SPLHOME}/etc/apps/.
elif [ "${action}" == "remove" ]; then
	ssh ${target} "rm -rf ${SPLHOME}/etc/apps/${app}"
else
  usage
fi
