#!/bin/bash

DIR=$(cd $(dirname $0); pwd -P)
source ${DIR}/config.sh
source ${DIR}/include.sh

function usage {
  echo "USAGE $(basename $0) clients"
  exit 1
}

if [ $# -lt 1 ]; then
  usage
fi

action="$1"

if [ "${action}" == "clients" ]; then
  while read line
  do
    if echo $line | grep "instanceId:" 2>/dev/null; then
      ID=$(echo $line | cut -d':' -f2 | sed -E 's, ,,g')
    fi
    if echo $line | grep "instanceName:" 2>/dev/null; then
      IN=$(echo $line | cut -d':' -f2 | sed -E 's, ,,g')
    fi
    if echo $line | grep "hostname:" 2>/dev/null; then
      HN=$(echo $line | cut -d':' -f2 | sed -E 's, ,,g')
    fi
    if echo $line | grep "dns:" 2>/dev/null; then
      DNS=$(echo $line | cut -d':' -f2 | sed -E 's, ,,g')
    fi
    if echo $line | grep "serverClasses:" 2>/dev/null; then
      CLASSES=$(echo $line | cut -d':' -f2 | sed -E 's, ,,g')
    fi
    printf "%s %s %s %s %s\n" "${ID}" "${IN}" "${HN}" "${DNS}" "${CLASSES}"
  done < <(${SPL} list deploy-clients)
else
  usage
fi
