#!/bin/bash

DIR=$(cd $(dirname $0); pwd -P)
source ${DIR}/config.sh
source ${DIR}/include.sh

TMP=$(mktemp)

cat > ${TMP} << EOF
export PATH=$PATH:~/bin
export PS1="[\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]]> "

alias stcd="cd ${SPLHOME}"
alias stcdsys="cd ${SPLHOME}/etc/system/local"
alias stcdapps="cd ${SPLHOME}/etc/apps"
EOF

exec bash --init-file ${TMP}
rm -f ${TMP}
